dataset:
  type: df
  name: ImageNet
  cvsfile: '/kaggle/input/cassava-leaf-disease-classification/train.csv'
  jsonfile: '/kaggle/input/cassava-leaf-disease-classification/label_num_to_disease_map.json'
  dataset_dir: '/kaggle/input/cassava-leaf-disease-classification/train_images'
  image_size: 224
  n_channels: 3
  n_classes: 50
model:
  type: imagenet
  name: efficientnet-b0
  pretrain: True
  pretrain_pth: None
augmentation:
  use_random_crop: True
  use_random_horizontal_flip: True
  use_cutout: False
  use_random_erasing: False
  use_dual_cutout: False
  use_mixup: False
  use_ricap: False
  use_cutmix: False
  use_label_smoothing: False
tta:
  use_resize: True
  use_center_crop: True
  resize: 256
train:
  output_dir: experiments/imagenet/efficientnet-b0/exp01
  use_apex: False
  batch_size: 8
scheduler:
  epochs: 20
  type: multistep
  milestones: [10, 20]
  lr_decay: 0.0001
validation:
  batch_size: 8

